title: Spiiin's blog
subtitle: ''
description: 'Programming blog'
keywords:
author: spiiin
language: ru
timezone: ''

url: http://spiiin.github.io
root: /
permalink: blog/:abbrlink/
abbrlink:
  alg: crc32
  rep: dec
  drafts: false
permalink_defaults:
pretty_urls:
  trailing_index: true
  trailing_html: true

source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

new_post_name: :title.md
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

index_generator:
  path: ''
  per_page: 8
  order_by: -date

default_category: uncategorized
category_map:
tag_map: 

meta_generator: true

date_format: YYYY-MM-DD
time_format: HH:mm:ss

use_date_for_updated: false

per_page: 25
pagination_dir: page

include:
exclude:
ignore:

kramed:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: true
  smartLists: true
  smartypants: true

server:
  compress: true

theme: pandollo
menu:
    Home: /
    Archive: /archives/
    Tags: /tags/meta
    About: /blog/1

favicon: /images/favicon.png
syntax_highlight: darkula
disqus: spiiin-github-io
googleAnalytics: UA-00000000-0

deploy:
  type: git
  repo: https://github.com/spiiin/spiiin.github.io
  branch: github-pages
  message: update blog
